### ISSUE TITLE
Runerror with function work_on_collection in SGVFinder.py 

### ISSUE THREAD

**Issue by pangkun97** [segalab/SGVFinder#19]
When I used SGVF_cmd.py  with paramaters: --min_samp_cutoff 1  --csv_output 'input_glob' 'output_dsgv' 'output_vsgv', it returned errors as follows:
```
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py:589: RuntimeWarning: divide by zero encountered in true_divide
  a/(b-1.0),
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py:593: RuntimeWarning: divide by zero encountered in true_divide
  a*(a+1.0)/((b-2.0)*(b-1.0)),
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:1037: RuntimeWarning: invalid value encountered in subtract
  mu2 = mu2p - mu * mu
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:2305: RuntimeWarning: invalid value encountered in double_scalars
  Lhat = muhat - Shat*mu
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/numpy/lib/function_base.py:1128: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/numpy/lib/function_base.py:3183: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/numpy/lib/function_base.py:3184: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)
Traceback (most recent call last):
  File "/User/software/SGVFinder-master/src/SGVF_cmd.py", line 47, in <module>
    args.vsgv_fit_method, args.x_coverage, args.rate_param, args.vsgv_dense_perc, args.browser_path)
  File "/User/software/SGVFinder-master/src/SGVFinder.py", line 168, in work_on_collection
    vsgv_fit_method, vsgv_dissim_thresh)
  File "/User/software/SGVFinder-master/src/SGVFinder.py", line 250, in find_sgvs
    sclusters = cluster_stretches(stretches, nodeldf, _spearman_dissim, dissim_thresh)
  File "/User/software/SGVFinder-master/src/SGVFinder.py", line 343, in cluster_stretches
    Z = linkage(distance, method = linkage_method)
  File "/User/miniconda3/envs/SVfinder/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 713, in linkage
    raise ValueError("The condensed distance matrix must contain only "
ValueError: The condensed distance matrix must contain only finite values.
```
The input files there were the output of ICRA_cmd.py and SGVF_PerFile_cmd.py with default parameters,
Could you help me fix this problem?

**Comment by nytwhzlg** [comment]
Do you have any solution? I have the same problem
