### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by ctseto** [segalab/SGVFinder#20]
Getting error 

FileNotFoundError: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-2.7/gem_qa.so'

Wondering what I've missed when installing dependencies. 

~/Programs/SGVFinder/src/cy_ext$ python setup.py build_ext
/home1/cseto/miniconda2/envs/SGVFinder/lib/python3.9/distutils/extension.py:131: UserWarning: Unknown Extension options: 'include_path'
  warnings.warn(msg)
running build_ext
skipping 'gem_qa.cpp' Cython extension (up-to-date)
skipping 'CSeqDict.cpp' Cython extension (up-to-date)
skipping 'Delta.c' Cython extension (up-to-date)
building 'gem_qa' extension
creating build
creating build/temp.linux-x86_64-3.9
gcc -pthread -B /home1/cseto/miniconda2/envs/SGVFinder/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home1/cseto/miniconda2/envs/SGVFinder/include -fPIC -O2 -isystem /home1/cseto/miniconda2/envs/SGVFinder/include -fPIC -I/home1/cseto/miniconda2/envs/SGVFinder/lib/python3.9/site-packages/numpy/core/include -I./ -I/home1/cseto/miniconda2/envs/SGVFinder/include/python3.9 -c gem_qa.cpp -o build/temp.linux-x86_64-3.9/gem_qa.o -std=c++11
In file included from /home1/cseto/miniconda2/envs/SGVFinder/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1944:0,
                 from /home1/cseto/miniconda2/envs/SGVFinder/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home1/cseto/miniconda2/envs/SGVFinder/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from gem_qa.cpp:625:
/home1/cseto/miniconda2/envs/SGVFinder/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
creating build/lib.linux-x86_64-3.9
g++ -pthread -B /home1/cseto/miniconda2/envs/SGVFinder/compiler_compat -Wl,--sysroot=/ -shared -Wl,-rpath,/home1/cseto/miniconda2/envs/SGVFinder/lib -Wl,-rpath-link,/home1/cseto/miniconda2/envs/SGVFinder/lib -L/home1/cseto/miniconda2/envs/SGVFinder/lib -Wl,-rpath,/home1/cseto/miniconda2/envs/SGVFinder/lib -Wl,-rpath-link,/home1/cseto/miniconda2/envs/SGVFinder/lib -L/home1/cseto/miniconda2/envs/SGVFinder/lib build/temp.linux-x86_64-3.9/gem_qa.o -o build/lib.linux-x86_64-3.9/gem_qa.cpython-39-x86_64-linux-gnu.so -std=c++11
building 'CSeqDict' extension
gcc -pthread -B /home1/cseto/miniconda2/envs/SGVFinder/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home1/cseto/miniconda2/envs/SGVFinder/include -fPIC -O2 -isystem /home1/cseto/miniconda2/envs/SGVFinder/include -fPIC -I/home1/cseto/miniconda2/envs/SGVFinder/include/python3.9 -c CSeqDict.cpp -o build/temp.linux-x86_64-3.9/CSeqDict.o -std=c++11
g++ -pthread -B /home1/cseto/miniconda2/envs/SGVFinder/compiler_compat -Wl,--sysroot=/ -shared -Wl,-rpath,/home1/cseto/miniconda2/envs/SGVFinder/lib -Wl,-rpath-link,/home1/cseto/miniconda2/envs/SGVFinder/lib -L/home1/cseto/miniconda2/envs/SGVFinder/lib -Wl,-rpath,/home1/cseto/miniconda2/envs/SGVFinder/lib -Wl,-rpath-link,/home1/cseto/miniconda2/envs/SGVFinder/lib -L/home1/cseto/miniconda2/envs/SGVFinder/lib build/temp.linux-x86_64-3.9/CSeqDict.o -o build/lib.linux-x86_64-3.9/CSeqDict.cpython-39-x86_64-linux-gnu.so -std=c++11
building 'Delta' extension
gcc -pthread -B /home1/cseto/miniconda2/envs/SGVFinder/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home1/cseto/miniconda2/envs/SGVFinder/include -fPIC -O2 -isystem /home1/cseto/miniconda2/envs/SGVFinder/include -fPIC -I/home1/cseto/miniconda2/envs/SGVFinder/include/python3.9 -c Delta.c -o build/temp.linux-x86_64-3.9/Delta.o
gcc -pthread -B /home1/cseto/miniconda2/envs/SGVFinder/compiler_compat -Wl,--sysroot=/ -shared -Wl,-rpath,/home1/cseto/miniconda2/envs/SGVFinder/lib -Wl,-rpath-link,/home1/cseto/miniconda2/envs/SGVFinder/lib -L/home1/cseto/miniconda2/envs/SGVFinder/lib -Wl,-rpath,/home1/cseto/miniconda2/envs/SGVFinder/lib -Wl,-rpath-link,/home1/cseto/miniconda2/envs/SGVFinder/lib -L/home1/cseto/miniconda2/envs/SGVFinder/lib build/temp.linux-x86_64-3.9/Delta.o -o build/lib.linux-x86_64-3.9/Delta.cpython-39-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/home1/cseto/Programs/SGVFinder/src/cy_ext/setup.py", line 11, in <module>
    shutil.copy('build/lib.linux-x86_64-2.7/gem_qa.so', 'gem_qa.so')
  File "/home1/cseto/miniconda2/envs/SGVFinder/lib/python3.9/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home1/cseto/miniconda2/envs/SGVFinder/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lib.linux-x86_64-2.7/gem_qa.so'

**Comment by talkorem** [comment]
This is a python version issue. We hope to soon release an official python 3 version (with many other improvements) but right now this is for python two. 
It seems that compilation was successful though, perhaps you could just find the .so files under build and move them to the src/cy_ext folder.

**Comment by treasure316** [comment]
Have you installed it successfully?
