### ISSUE TITLE
jsdel input cmd line issues

### ISSUE THREAD

**Issue by ctseto** [segalab/SGVFinder#22]
For the second part, having issues with generating output via SGVF_PerFile_cmd.py .

python ../SGVF_PerFile_cmd.py C0.jsdel outputs 150
Traceback (most recent call last):
  File "../SGVF_PerFile_cmd.py", line 22, in <module>
    mp = get_sample_map(args.deltaf, args.x_coverage, args.average_read_length, args.rate_param)
  File "/mnt/home1/cseto/Programs/SGVFinder/src/SGVFinder.py", line 32, in get_sample_map
    ind1 = int((pos1 + (average_read_length / 2)) / bin_size)
TypeError: unsupported operand type(s) for /: 'str' and 'int'

Additionally, having issues with calling it directly in python. When I refactor linear_example, samp_to_map to seems to work fine. Executing work_on_collection, the resultant files (vsgv, dsgv) appear to be blank, and the input samp_to_map for work_on_collection seems like it should be fine.

**Comment by wanjinhu** [comment]
because the script `SGVFinder.py` and `SGVF_cmd.py` had several bugs need to be fixed. 
you can find the solution below:
https://github.com/GRONINGEN-MICROBIOME-CENTRE/Groningen-Microbiome/tree/master/Scripts/SV_pipeline
