### ISSUE TITLE
Index error when running SGVF_PerFile_cmd.py

### ISSUE THREAD

**Issue by liuronghyw** [segalab/SGVFinder#27]
To whom it may cancern,
     Thanks for your excellent work!
    When I run the following code "/public/home/hpc4011032/.conda/envs/SVGFinder_env/bin/python2.7 /public/home/hpc4011032/soft/SVGFinder/DataFiles/SGVF_PerFile_cmd.py \
./ICRA/ERR2213726_kneaddata.jsdel ./IRCA/temp/ERR2213678.jsdel 150" 

   I found error as follows."

   ./ICRA/ERR2213726_kneaddata.jsdel ./IRCA/temp/ERR2213726.jsdel 150
Traceback (most recent call last):
  File "/public/home/hpc4011032/soft/SVGFinder/DataFiles/SGVF_PerFile_cmd.py", line 22, in <module>
    mp = get_sample_map(args.deltaf, args.x_coverage, args.average_read_length, args.rate_param)
  File "/public/home/hpc4011032/soft/SVGFinder/DataFiles/SGVFinder.py", line 37, in get_sample_map
    bacid_maps[dest_id][ind1] += used_koef
IndexError: index 4917 is out of bounds for axis 0 with size 4917"

   Dose anyone can help? Thanks!

**Comment by yilmazbah** [comment]
Did you manage to solve the problem? I came across the same issue.
