### ISSUE TITLE
Problome of SGVF_cmd.py

### ISSUE THREAD

**Issue by treasure316** [segalab/SGVFinder#30]
Dear professor，
I encountered the following error while doing SV comparison. I have not encountered any error in analyzing other data before. Do you know how to solve it？
![Uploading mmexport1697101499494.png…]()

**Comment by talkorem** [comment]
Hello,
The image you shared is not loading correctly, so I cannot see what the error is. Please note that this package is not actively maintained. You're welcome to check out https://github.com/korem-lab/SGVFinder2.

**Comment by treasure316** [comment]
Dear professor，.I am writing to seek your assistance regarding an error I encountered during SV alignment. Previously, I have not encountered such an issue while analyzing other datasets.

Currently, I am analyzing a dataset comprising 190 samples. However, only 83 samples have successfully aligned with dsv and vsv,and no error reported . I am unsure why only 83 samples have successfully aligned with dsv and vsv,and.
When I attempted to align a subset of samples from the 190, the error I encountered was as follows.
I wanted to inquire if you have encountered a similar issue before and if so, how did you resolve it? Your expertise and guidance would be greatly appreciated.




The error:python /mnt/nfs/5110v5/jiangxin/code/SGV_finder/src/SGVF_cmd.py 'result/SGV/sgv1/tmp/*.jsdel' \
> result/SGV/sgv1/deletion-sgv.csv result/SGV/sgv1/variable-sgv.csv \
> --x_coverage 0.01 --rate_param 10 --min_samp_cutoff 1 --dels_detect_thresh 0.25 --real_del_thresh 0.95 \
> --vsgv_dissim_thresh 0.125 --dels_cooc_thresh 0.25 --vsgv_clip_quantile 0.02 --vsgv_fit_interval 0.95 \
> --vsgv_fit_method 'betaprime' --vsgv_dense_perc 85 --csv_output --byorig \
> --browser_path result/SGV/sgv1/html
/mnt/nfs/5110v5/jiangxin/miniconda_3/miniconda3/envs/SGV/lib/python2.7/site-packages/numpy/lib/function_base.py:4033: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)
Traceback (most recent call last):
  File "/mnt/nfs/5110v5/jiangxin/code/SGV_finder/src/SGVF_cmd.py", line 43, in <module>
    samp_to_map, args.real_del_thresh, args.vsgv_dense_perc, args.browser_path, args.x_coverage, args.rate_param)
  File "/mnt/nfs/5110v5/jiangxin/code/SGV_finder/src/SGVFinder.py", line 126, in calculate_by_other
    deldf, delsregions_, bacdf, sgvregions, weboutputdir, genepos)
  File "/mnt/nfs/5110v5/jiangxin/code/SGV_finder/src/SGVFinder.py", line 371, in draw_one_region
    drawdf = DataFrame({i:normdf[i] if i in normdf.columns else np.nan for i in bacdf.columns})
  File "/mnt/nfs/5110v5/jiangxin/miniconda_3/miniconda3/envs/SGV/lib/python2.7/site-packages/pandas/core/frame.py", line 348, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/mnt/nfs/5110v5/jiangxin/miniconda_3/miniconda3/envs/SGV/lib/python2.7/site-packages/pandas/core/frame.py", line 459, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/mnt/nfs/5110v5/jiangxin/miniconda_3/miniconda3/envs/SGV/lib/python2.7/site-packages/pandas/core/frame.py", line 7356, in _arrays_to_mgr
    index = extract_index(arrays)
File "/mnt/nfs/5110v5/jiangxin/miniconda_3/miniconda3/envs/SGV/lib/python2.7/site-packages/pandas/core/frame.py", line 7393, in extract_index
    raise ValueError('If using all scalar values, you must pass'
ValueError: If using all scalar values, you must pass an index

**Comment by 12345yzk** [comment]
i also encounter this error：ValueError: If using all scalar values, you must pass an index

**Comment by chenolaf** [comment]
> 我还遇到了这个错误：ValueError：如果使用所有标量值，必须传递索引

Me too，i have trouble 😭
