### ISSUE TITLE
When run "work_on_collection" got some issues

### ISSUE THREAD

**Issue by nytwhzlg** [segalab/SGVFinder#35]
Hello, I'm having trouble running "work_on_collection." 
Below is the error message I'm receiving. 
Could you please provide me with a solution?

Traceback (most recent call last):
  File "/home/miniconda3/envs/sgv_finder2_0.0.1/bin/svfinder", line 8, in <module>
    sys.exit(run())
  File "/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/SGVFinder2/cli/svfinder_cli.py", line 95, in run
    vsgv, dsgv = work_on_collection(
  File "/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/SGVFinder2/svfinder.py", line 229, in work_on_collection
    sgvregions, normdf = find_sgvs(bacdf, max_spacing, vsgv_dense_perc, bacname, deldf,
  File "/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/SGVFinder2/svfinder.py", line 321, in find_sgvs
    sclusters = cluster_stretches(stretches, nodeldf, _spearman_dissim, dissim_thresh, 'complete')
  File "/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/SGVFinder2/svfinder.py", line 429, in cluster_stretches
    Z = linkage(distance, method=linkage_method)
  File "/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/scipy/cluster/hierarchy.py", line 1064, in linkage
    raise ValueError("The condensed distance matrix must contain only "
ValueError: The condensed distance matrix must contain only finite values.

**Comment by nytwhzlg** [comment]
Above that have some warning messages as these:

/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/scipy/stats/_stats_py.py:5445: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(warn_msg))
/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/scipy/stats/_stats_py.py:5445: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(warn_msg))
/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/scipy/stats/_stats_py.py:5445: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(warn_msg))
/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/scipy/stats/_stats_py.py:5445: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(warn_msg))
/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/scipy/stats/_stats_py.py:5445: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(warn_msg))
/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/scipy/stats/_stats_py.py:5445: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(warn_msg))
/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/scipy/stats/_stats_py.py:5445: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(warn_msg))
/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/scipy/stats/_stats_py.py:5445: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(warn_msg))
/home/miniconda3/envs/sgv_finder2_0.0.1/lib/python3.10/site-packages/scipy/stats/_stats_py.py:5445: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(warn_msg))
