### ISSUE TITLE
ICRA.py ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by thejiahaozhang** [segalab/SGVFinder#4]
![image](https://user-images.githubusercontent.com/50943892/58675113-75196b80-8385-11e9-966a-7f80ae047a99.png)
Hello.
I have encountered some problems.
What are the causes of these problems?
IndexError: index 1 is out of bounds for axis 0 with size 1
Exception IndexError: 'index 1 is out of bounds for axis 0 with size 1' in 'gem_qa.calc_quality' ignored
Traceback (most recent call last):
  File "./SVGF/SGVFinder-master/src/ICRA_cmd.py", line 46, in <module>
    args.length_maximum, args.usage, args.use_theta)
  File "./SVGF/SGVFinder-master/src/ICRA.py", line 32, in single_file
    dense_region_coverage, dest_dictf, use_theta)
  File "./SVGF/SGVFinder-master/src/ICRAUtils.py", line 21, in timed
    result = method(*args, **kw)
  File "./SVGF/SGVFinder-master/src/ICRA.py", line 58, in _initialize
    pi = read_container.get_pi()
  File "./SVGF/SGVFinder-master/src/ReadContainer.py", line 113, in get_pi
    pi[r[_r_DEST]] += r[r_QUALITY] / qual_sum
ZeroDivisionError: float division by zero

Best Wish!

**Comment by talkr** [comment]
Can you share the pmp file?

**Comment by thejiahaozhang** [comment]
I'm so sorry that I can't upload this file.(pmp file has 3.87gb)
Fastq file has 17.97gb
When I choose the first 50,000 lines, it has no problem.
When I choose to a fastq file(3.58gb), it has no problem.

**Comment by talkr** [comment]
Send me an e-mail to tal <dot> korem at gmail

**Comment by talkr** [comment]
Send me an email to tal<dot>Korem at gmail.

**Comment by HaoranPeng21** [comment]
Hi, How is it being solved,  I encountered the same problem.

**Comment by liuronghyw** [comment]
Hi, How is it being solved, I encountered the same problem.

**Comment by liuronghyw** [comment]
> Send me an e-mail to tal korem at gmail

Hi, Koren; Would you please tell me your e-mail, I encounter this problem and can't solved. Thanks!

**Comment by liuronghyw** [comment]
> I'm so sorry that I can't upload this file.(pmp file has 3.87gb) Fastq file has 17.97gb When I choose the first 50,000 lines, it has no problem. When I choose another fastq file (3.58gb), it has no problem.

Hi, Dr. Zhang, would you please give me some hints on how to solve this problem? Thanks!

**Comment by liuronghyw** [comment]
> Hello. I have encountered some problems. What are the causes of these problems? IndexError: index 1 is out of bounds for axis 0 with size 1 Exception IndexError: 'index 1 is out of bounds for axis 0 with size 1' in 'gem_qa.calc_quality' ignored Traceback (most recent call last): File "./SVGF/SGVFinder-master/src/ICRA_cmd.py", line 46, in args.length_maximum, args.usage, args.use_theta) File "./SVGF/SGVFinder-master/src/ICRA.py", line 32, in single_file dense_region_coverage, dest_dictf, use_theta) File "./SVGF/SGVFinder-master/src/ICRAUtils.py", line 21, in timed result = method(*args, **kw) File "./SVGF/SGVFinder-master/src/ICRA.py", line 58, in _initialize pi = read_container.get_pi() File "./SVGF/SGVFinder-master/src/ReadContainer.py", line 113, in get_pi pi[r[_r_DEST]] += r[r_QUALITY] / qual_sum ZeroDivisionError: float division by zero
> 
> Best Wish!

Hello, you asked this question before, but I met the same problem. Have you solved it?

Thank you!
Best wishes!

**Comment by chenolaf** [comment]
> Hi, How is it being solved, I encountered the same problem.

Hello,Dear Professor, would you please give me some hints on how to solve this problem? Thanks! Did you change the file "./SVGF/SGVFinder-master/src/ReadContainer.py"?

Thank you!
Best wishes!
